name: 'github-notify-action'
description: 'Integrate im webhooks'
author: 'fatelei'
inputs:
  webhook:
    required: true
    description: 'webhook url'
  message_type:
    required: true
    description: 'message type, current only support text'
  content:
    required: true
    description: 'what text is sended'
runs:
  using: 'node12'
  main: 'dist/index.js'
