name: 'github-notify-action'
description: 'Integrate im webhooks'
author: 'fatelei'
inputs:
  integration:
    required: true
    description: 'support lark / wecom'
  webhook:
    required: true
    description: 'webhook url'
  messageType:
    required: true
    description: 'message type, current only support text'
  title:
    required: false
    description: 'title'
    default: ''
  content:
    required: true
    description: 'content'
runs:
  using: 'node12'
  main: 'dist/index.js'
